name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use a versão v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Use a versão v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_readme.py
